### ISSUE TITLE
cannot parse proxy setting

### ISSUE THREAD

**Issue by mdcoolcat** [forcedotcom/Analytics-Cloud-Dataset-Utils#16]
I want to add SFM proxy to settings.json, my setting like this:
{
  "proxyUsername" : null,
  "proxyPassword" : null,
  "proxyNtlmDomain" : null,
  "proxyHost" : public-proxy1-0-sfm.data.sfdc.net,
  "proxyPort" : 8080,
  "timeoutSecs" : 540,
  "connectionTimeoutSecs" : 60,
  "noCompression" : false,
  "debugMessages" : false
}

And it's complaining the value I put:
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'public': was expecting ('true', 'false' or 'null')
 at [Source: java.io.InputStreamReader@7ca48474; line: 6, column: 23]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1524)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:557)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2042)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1412)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:679)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:235)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2993)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2121)
	at com.sforce.dataset.DatasetUtilConstants.getSystemConfig(DatasetUtilConstants.java:242)
	at com.sforce.dataset.util.DatasetUtils.getConnectorConfig(DatasetUtils.java:551)
	at com.sforce.dataset.util.DatasetUtils.login(DatasetUtils.java:457)
	at com.sforce.dataset.DatasetUtilMain.main(DatasetUtilMain.java:377)

Isn't proxyHost and proxyPort the places I put proxy value?

**Comment by datasetutil** [comment]
I think json parser, expects sring values to be quoted, else it assumes its boolean

**Comment by mdcoolcat** [comment]
Thanks my bad. Added quote and works now
