### ISSUE TITLE
Java Class Cast Exception

### ISSUE THREAD

**Issue by dmelloreema** [forcedotcom/Analytics-Cloud-Dataset-Utils#39]
Hi, 
I am using the datasetutils and am receiving the following error message. I tried the earlier of datasetutils-37 which also produced the same error message. 

" java.class.path:datasetutils-39.0.1.jar
SystemClassLoader:Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at com.sforce.dataset.DatasetUtilMain.printClasspath(DatasetUtilMain.java:1204)
        at com.sforce.dataset.DatasetUtilMain.main(DatasetUtilMain.java:79)" 

I appreciate any help/guidance. 

Thanks!

**Comment by spencerkoo** [comment]
@dmelloreema What version of Java are you using? Java 8 or 9? I've had this issue before and Java 9 appears to break it. Uninstall Java 9 and downgrade to whatever the latest version of 8. I believe it's 1.8.162.
