### ISSUE TITLE
Can't start server mode 32.0.22

### ISSUE THREAD

**Issue by mdhari** [forcedotcom/Analytics-Cloud-Dataset-Utils#6]
Getting this exception when trying to start it:

$ java -jar datasetutils-32.0.22.jar --server true

		****************************************
		Salesforce Analytics Cloud Dataset Utils
		****************************************

*******************************************************************************
2015-05-13 13:02:43.423:INFO::main: Logging initialized @135ms
2015-05-13 13:02:43.493:INFO:oejs.Server:main: jetty-9.2.z-SNAPSHOT
2015-05-13 13:02:43.532:WARN:oejw.WebInfConfiguration:main: Web application not found src/main/webapp
2015-05-13 13:02:43.532:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@21588809{/,null,null}{src/main/webapp}
java.io.FileNotFoundException: src/main/webapp
	at org.eclipse.jetty.webapp.WebInfConfiguration.unpack(WebInfConfiguration.java:493)
	at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:72)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:464)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:500)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.sforce.dataset.server.DatasetUtilServer.init(DatasetUtilServer.java:91)
	at com.sforce.dataset.DatasetUtilMain.main(DatasetUtilMain.java:253)
2015-05-13 13:02:43.562:INFO:oejs.ServerConnector:main: Started ServerConnector@75828a0f{HTTP/1.1}{127.0.0.1:3174}
2015-05-13 13:02:43.562:INFO:oejs.Server:main: Started @277ms
*******************************************************************************

Enter 0  to Exit:

**Comment by datasetutil** [comment]
Uploaded a new version! Please try with that and let me know
